### ISSUE TITLE
[ISSUE] Unable to import skins to bedrock.

### ISSUE THREAD

**Issue by ghost** [FlavioGarciaDev/MinecraftSkinPackCreator#1]
I compiled a skin pack and minecraft throws an error but nothing in the logs. Here’s my pack
[new.zip](https://github.com/FlavioGarciaDev/MinecraftSkinPackCreator/files/5513852/new.zip)

**Comment by ghost** [comment]
Oh, I forgot to mention this but I could help if you run into a problem with coding(i know my fair share).

**Comment by FlavioGarciaDev** [comment]
Weird, I tried and your pack works just fine. But I'm on Windows 10.

![image](https://user-images.githubusercontent.com/29122275/98610463-63ecc200-22ce-11eb-9acd-3bc578218494.png)

Are you on OSX right? I never tried there. I just fails the importing, no error messages whatsoever?
Can you locate the Minecraft installation folder and check the skin_packs subfolder?

**Comment by ghost** [comment]
This is what I got.
![image](https://user-images.githubusercontent.com/70609400/98611483-018cc500-22c0-11eb-9d39-0e7c28410472.png)
I did find a folder, the name was incomplete and kept on spamming me with 'Failed to import'

**Comment by FlavioGarciaDev** [comment]
Take a look at this, it looks like the same scenario we have right now: https://www.reddit.com/r/MCPE/comments/b4vi5a/problem_importing_a_mcpack_addon_on_ipad/

Can you try it?

**Comment by ghost** [comment]
Oh and I'm on bedrock pe, I suspect it's an issue with the pack generation as older packs don't work with the 1.16.50 hotfix.
(I'm on IPadOS)

**Comment by ghost** [comment]
Oh, I tried that before and it didn't work, the folder has to be the same name as the resource pack .mc file, Thanks!

**Comment by splapoon** [comment]
![Uploading 98612274...]

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/70609400/98612286-d905ca80-22c1-11eb-9f66-304f22446dda.png)

**Comment by FlavioGarciaDev** [comment]
> 
> 
> Oh, I tried that before and it didn't work, the folder has to be the same name as the resource pack .mc file, Thanks!

Maybe it was the special characters in the name? I know there's a name length limit, but during the import it's usually automatically handled.

**Comment by ghost** [comment]
It was most likely my assumption that because the world folder names are wacky(base 32 iirc) that they would be. 
EDIT:scratch that, tl;dr it won't import make a folder the name of your file and extract in there
(alike rename new.mcpack to new.zip make a folder called new and extract in that
