### ISSUE TITLE
HOW DO YOU DOWNLOAD IT?

### ISSUE THREAD

**Issue by TROVEL32** [FlavioGarciaDev/MinecraftSkinPackCreator#16]
:(

**Comment by FlavioGarciaDev** [comment]
Click on Releases on right side, then you will see a "Assets" section right below the latest release. Download the zip file, extract and run the application.

**Comment by AnonymousDab84** [comment]
Thank you for taking the time to reply I swear I always have issues with
the site it's user error I know that's what makes it annoying 😆
