### ISSUE TITLE
Error saving

### ISSUE THREAD

**Issue by JDOGGOKUSSJ2** [FlavioGarciaDev/MinecraftSkinPackCreator#3]
when I click save it says an error occurred
![2021-01-26_225545](https://user-images.githubusercontent.com/78064494/105940640-c631a500-6029-11eb-9e1b-52285a178391.png)

**Comment by FlavioGarciaDev** [comment]
I will look into it.

**Comment by FlavioGarciaDev** [comment]
Fixed in the 1.1.1 release!
