### ISSUE TITLE
starting

### ISSUE THREAD

**Issue by dukeluc** [FlavioGarciaDev/MinecraftSkinPackCreator#9]
Where is 'MinecraftSkinPackCreator.exe' located because i can't find it.

**Comment by FlavioGarciaDev** [comment]
Go to Releases, download the [MinecraftSkinPackCreator_win_111.zip, or click here](https://github.com/FlavioGarciaDev/MinecraftSkinPackCreator/releases/download/1.1.1/MinecraftSkinPackCreator_win_111.zip). Then extract and run the 'MinecraftSkinPackCreator.exe'.

![image](https://user-images.githubusercontent.com/29122275/156919729-9eb22289-f388-4b3c-802c-baf82810bdeb.png)
